#!/bin/bash 
echo "Hello, World!"
start firefox https://youtu.be/FqtzUjT02K0 
start firefox https://en.wikipedia.org/wiki/Greeting
start firefox https://www.virtualpilotlight.com/ 
start firefox https://en.wikipedia.org/wiki/%22Hello%2C_World!%22_program
start firefox https://youtu.be/CZClBsDpp-4
start firefox https://en.wikipedia.org/wiki/Video
start firefox https://en.wikipedia.org/wiki/Today
start firefox https://en.wikipedia.org/wiki/5000
start firefox https://en.wikipedia.org/wiki/Powerman_5000
start firefox https://en.wikipedia.org/w/index.php?title=140_characters&redirect=no
start firefox https://www.merriam-webster.com/dictionary/disseminate
start firefox https://en.wikipedia.org/wiki/The_5,000_Fingers_of_Dr._T.
start firefox https://en.wikipedia.org/wiki/Dr._Seuss
start firefox https://en.wikipedia.org/w/index.php?title=Movie&redirect=no
start firefox https://en.wikipedia.org/wiki/A_Movie
start firefox https://archive.org/details/a-movie-dir.-bruce-conner-1958.
start firefox https://en.wikipedia.org/wiki/Piano
start firefox https://en.wikipedia.org/wiki/Teacher
start firefox https://en.wikipedia.org/wiki/Captive_audience
start firefox https://en.wikipedia.org/wiki/Snaps
start firefox https://www.merriam-webster.com/dictionary/teetotaler
start firefox https://www.merriam-webster.com/dictionary/obliged
start firefox https://en.wikipedia.org/wiki/Personal_branding
start firefox https://en.wikipedia.org/wiki/Prerequisite
start firefox https://en.wikipedia.org/wiki/Shape
start firefox https://en.wikipedia.org/wiki/Script
start firefox https://en.wikipedia.org/wiki/Web_browser
start firefox https://en.wikipedia.org/wiki/Textual_criticism#External_evidence
start firefox https://frinkiac.com/video/S07E06/mnEpxuUNgsZAUg3G5ncRrHH0iQo=.gif
start firefox https://www.merriam-webster.com/dictionary/rude
start firefox https://www.urbandictionary.com/define.php?term=Basic
start firefox https://en.wikipedia.org/wiki/BASIC
start firefox https://morbotron.com/video/S05E05/yMhkWI4kcPDDFOR1YtgM9_G6GS4=.gif
start firefox https://en.wikipedia.org/wiki/Base_\(chemistry\)
start firefox https://media.giphy.com/media/3o7TKAZnIu4w31OqmA/giphy.gif
start firefox https://en.wikipedia.org/wiki/USB
start firefox https://en.wikipedia.org/wiki/Automation
start firefox https://en.wikipedia.org/wiki/Closed_captioning
start firefox https://en.wikipedia.org/wiki/Words_per_minute
start firefox https://play.typeracer.com/ 
start firefox https://en.wikipedia.org/wiki/5
start firefox https://www.instagram.com/virtualpilotlight/
start firefox https://en.wikipedia.org/wiki/Coffin
start firefox https://www.arduino.cc/
start firefox https://www.adafruit.com/
start firefox https://en.wikipedia.org/wiki/Soldering
start firefox https://en.wikipedia.org/wiki/Light-emitting_diode
start firefox https://www.smooth-on.com/products/task-9/
start firefox https://en.wikipedia.org/wiki/Plan_9_from_Outer_Space 
start firefox https://en.wikipedia.org/wiki/Compressed_air
start firefox https://en.wikipedia.org/wiki/Phlebotomy
start firefox https://en.wikipedia.org/wiki/Disability
start firefox https://en.wikipedia.org/wiki/What%27s_Up%3F_\(4_Non_Blondes_song\)
start firefox https://en.wikipedia.org/wiki/Lyudi_Invalidy
start firefox https://www.merriam-webster.com/dictionary/vertical
start firefox https://en.wikipedia.org/wiki/Full-time_job
start firefox https://en.wikipedia.org/wiki/Bene_Gesserit#Litany_against_fear
start firefox https://en.wikipedia.org/wiki/Five_Minutes
start firefox https://en.wikipedia.org/wiki/Bash_\(Unix_shell\)
start firefox https://en.wikipedia.org/wiki/Hardening_\(computing\)
start firefox https://en.wikipedia.org/wiki/Linux
start firefox https://www.urbandictionary.com/define.php?term=wet%20pantie
start firefox https://github.com/
start firefox https://www.urbandictionary.com/define.php?term=customer%20service%20voice
start firefox https://en.wikipedia.org/wiki/Lip_service