#!/bin/bash 
echo "Hello, World!"
sensible-browser https://youtu.be/FqtzUjT02K0 
sensible-browser https://en.wikipedia.org/wiki/Greeting
sensible-browser https://www.virtualpilotlight.com/ 
sensible-browser https://en.wikipedia.org/wiki/%22Hello%2C_World!%22_program
sensible-browser https://youtu.be/CZClBsDpp-4
sensible-browser https://en.wikipedia.org/wiki/Video
sensible-browser https://en.wikipedia.org/wiki/Today
sensible-browser https://en.wikipedia.org/wiki/5000
sensible-browser https://en.wikipedia.org/wiki/Powerman_5000
sensible-browser https://en.wikipedia.org/w/index.php?title=140_characters&redirect=no
sensible-browser https://www.merriam-webster.com/dictionary/disseminate
sensible-browser https://en.wikipedia.org/wiki/The_5,000_Fingers_of_Dr._T.
sensible-browser https://en.wikipedia.org/wiki/Dr._Seuss
sensible-browser https://en.wikipedia.org/w/index.php?title=Movie&redirect=no
sensible-browser https://en.wikipedia.org/wiki/A_Movie
sensible-browser https://archive.org/details/a-movie-dir.-bruce-conner-1958.
sensible-browser https://en.wikipedia.org/wiki/Piano
sensible-browser https://en.wikipedia.org/wiki/Teacher
sensible-browser https://en.wikipedia.org/wiki/Captive_audience
sensible-browser https://en.wikipedia.org/wiki/Snaps
sensible-browser https://www.merriam-webster.com/dictionary/teetotaler
sensible-browser https://www.merriam-webster.com/dictionary/obliged
sensible-browser https://en.wikipedia.org/wiki/Personal_branding
sensible-browser https://en.wikipedia.org/wiki/Prerequisite
sensible-browser https://en.wikipedia.org/wiki/Shape
sensible-browser https://en.wikipedia.org/wiki/Script
sensible-browser https://en.wikipedia.org/wiki/Web_browser
sensible-browser https://en.wikipedia.org/wiki/Textual_criticism#External_evidence
sensible-browser https://frinkiac.com/video/S07E06/mnEpxuUNgsZAUg3G5ncRrHH0iQo=.gif
sensible-browser https://www.merriam-webster.com/dictionary/rude
sensible-browser https://www.urbandictionary.com/define.php?term=Basic
sensible-browser https://en.wikipedia.org/wiki/BASIC
sensible-browser https://morbotron.com/video/S05E05/yMhkWI4kcPDDFOR1YtgM9_G6GS4=.gif
sensible-browser https://en.wikipedia.org/wiki/Base_\(chemistry\)
sensible-browser https://media.giphy.com/media/3o7TKAZnIu4w31OqmA/giphy.gif
sensible-browser https://en.wikipedia.org/wiki/USB
sensible-browser https://en.wikipedia.org/wiki/Automation
sensible-browser https://en.wikipedia.org/wiki/Closed_captioning
sensible-browser https://en.wikipedia.org/wiki/Words_per_minute
sensible-browser https://play.typeracer.com/ 
sensible-browser https://en.wikipedia.org/wiki/5
sensible-browser https://www.instagram.com/virtualpilotlight/
sensible-browser https://en.wikipedia.org/wiki/Coffin
sensible-browser https://www.arduino.cc/
sensible-browser https://www.adafruit.com/
sensible-browser https://en.wikipedia.org/wiki/Soldering
sensible-browser https://en.wikipedia.org/wiki/Light-emitting_diode
sensible-browser https://www.smooth-on.com/products/task-9/
sensible-browser https://en.wikipedia.org/wiki/Plan_9_from_Outer_Space 
sensible-browser https://en.wikipedia.org/wiki/Compressed_air
sensible-browser https://en.wikipedia.org/wiki/Phlebotomy
sensible-browser https://en.wikipedia.org/wiki/Disability
sensible-browser https://en.wikipedia.org/wiki/What%27s_Up%3F_\(4_Non_Blondes_song\)
sensible-browser https://en.wikipedia.org/wiki/Lyudi_Invalidy
sensible-browser https://www.merriam-webster.com/dictionary/vertical
sensible-browser https://en.wikipedia.org/wiki/Full-time_job
sensible-browser https://en.wikipedia.org/wiki/Bene_Gesserit#Litany_against_fear
sensible-browser https://en.wikipedia.org/wiki/Five_Minutes
sensible-browser https://en.wikipedia.org/wiki/Bash_\(Unix_shell\)
sensible-browser https://en.wikipedia.org/wiki/Hardening_\(computing\)
sensible-browser https://en.wikipedia.org/wiki/Linux
sensible-browser https://www.urbandictionary.com/define.php?term=wet%20pantie
sensible-browser https://github.com/
sensible-browser https://www.urbandictionary.com/define.php?term=customer%20service%20voice
sensible-browser https://en.wikipedia.org/wiki/Lip_service
