#!/bin/bash 
sensible-browser https://youtu.be/jcEXPlhLqcg 
sensible-browser https://youtu.be/o-sp68GjYL0
sensible-browser https://en.wikipedia.org/wiki/Welcome
sensible-browser https://en.wikipedia.org/wiki/Welcome_\(disambiguation\)
sensible-browser https://www.virtualpilotlight.com/
sensible-browser https://en.wikipedia.org/wiki/Virtual
sensible-browser https://en.wikipedia.org/wiki/Virtual_Light
sensible-browser https://en.wikipedia.org/wiki/Pilot_light
sensible-browser https://en.wikipedia.org/wiki/Video
sensible-browser https://en.wikipedia.org/wiki/First
sensible-browser https://en.wikipedia.org/wiki/Script
sensible-browser https://en.wikipedia.org/wiki/Script_\(Unix\)
sensible-browser https://en.wikipedia.org/wiki/Unix
sensible-browser https://en.wikipedia.org/wiki/Work
sensible-browser https://en.wikipedia.org/wiki/Yeah
sensible-browser https://en.wikipedia.org/wiki/Hope
sensible-browser https://en.wikipedia.org/wiki/Persephone
sensible-browser https://docs.github.com/en/get-started
sensible-browser https://en.wikipedia.org/wiki/Clone
sensible-browser https://en.wikipedia.org/wiki/Fork_\(system_call\)
sensible-browser https://en.wikipedia.org/wiki/System_call
sensible-browser https://en.wikipedia.org/wiki/Fork_bomb
sensible-browser https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository
sensible-browser https://docs.github.com/en/repositories
sensible-browser https://en.wikipedia.org/wiki/Run_command
sensible-browser https://en.wikipedia.org/wiki/Computer
sensible-browser https://en.wikipedia.org/wiki/Personal_computer
sensible-browser https://en.wikipedia.org/wiki/1
sensible-browser https://en.wikipedia.org/wiki/Time
sensible-browser https://www.merriam-webster.com/dictionary/obvious
sensible-browser https://www.merriam-webster.com/dictionary/oblivious
sensible-browser https://www.merriam-webster.com/dictionary/contained
sensible-browser https://en.wikipedia.org/wiki/Containerization
sensible-browser https://en.wikipedia.org/wiki/Containerization_\(computing\)
sensible-browser https://en.wikipedia.org/wiki/OS-level_virtualization
sensible-browser https://en.wikipedia.org/wiki/Operating_system
sensible-browser https://en.wikipedia.org/wiki/Kernel_\(operating_system\)
sensible-browser https://en.wikipedia.org/wiki/Virtualization
sensible-browser https://en.wikipedia.org/wiki/Virtual_machine
sensible-browser https://en.wikipedia.org/wiki/Work_of_art
sensible-browser https://en.wikipedia.org/wiki/Glossary_of_music_terminology#M
sensible-browser https://www.merriam-webster.com/dictionary/concurrently
sensible-browser https://www.merriam-webster.com/dictionary/trivially
sensible-browser https://en.wikipedia.org/wiki/Trivialism
sensible-browser https://twitter.com/iancoldwater/status/1403019325032779781?lang=en
sensible-browser https://en.wikipedia.org/wiki/Privilege_escalation
sensible-browser https://en.wikipedia.org/wiki/Accompaniment
sensible-browser https://en.wikipedia.org/wiki/Spoiler
sensible-browser https://en.wikipedia.org/wiki/Experience
sensible-browser https://www.merriam-webster.com/dictionary/minor
sensible-browser https://en.wikipedia.org/wiki/Break_in
sensible-browser https://www.merriam-webster.com/dictionary/say
sensible-browser https://www.merriam-webster.com/dictionary/out%20loud
sensible-browser https://www.urbandictionary.com/define.php?term=mind%20bottling
sensible-browser https://www.merriam-webster.com/dictionary/update
sensible-browser https://en.wikipedia.org/wiki/Update_\(SQL\)
sensible-browser https://en.wikipedia.org/wiki/Create,_read,_update_and_delete
sensible-browser https://en.wikipedia.org/wiki/Desktop_computer
sensible-browser https://en.wikipedia.org/wiki/Linux
sensible-browser https://en.wikipedia.org/wiki/Microsoft_Windows
sensible-browser https://en.wikipedia.org/wiki/Verification_and_validation
sensible-browser https://en.wikipedia.org/wiki/Copy
sensible-browser https://en.wikipedia.org/wiki/Xerox
sensible-browser https://en.wikipedia.org/wiki/Toaster_Strudel
sensible-browser https://www.merriam-webster.com/dictionary/ready
sensible-browser https://en.wikipedia.org/wiki/Minced_oath
