#!/bin/bash 
start firefox https://youtu.be/jcEXPlhLqcg 
start firefox https://youtu.be/o-sp68GjYL0
start firefox https://en.wikipedia.org/wiki/Welcome
start firefox https://en.wikipedia.org/wiki/Welcome_\(disambiguation\)
start firefox https://www.virtualpilotlight.com/
start firefox https://en.wikipedia.org/wiki/Virtual
start firefox https://en.wikipedia.org/wiki/Virtual_Light
start firefox https://en.wikipedia.org/wiki/Pilot_light
start firefox https://en.wikipedia.org/wiki/Video
start firefox https://en.wikipedia.org/wiki/First
start firefox https://en.wikipedia.org/wiki/Script
start firefox https://en.wikipedia.org/wiki/Script_\(Unix\)
start firefox https://en.wikipedia.org/wiki/Unix
start firefox https://en.wikipedia.org/wiki/Work
start firefox https://en.wikipedia.org/wiki/Yeah
start firefox https://en.wikipedia.org/wiki/Hope
start firefox https://en.wikipedia.org/wiki/Persephone
start firefox https://docs.github.com/en/get-started
start firefox https://en.wikipedia.org/wiki/Clone
start firefox https://en.wikipedia.org/wiki/Fork_\(system_call\)
start firefox https://en.wikipedia.org/wiki/System_call
start firefox https://en.wikipedia.org/wiki/Fork_bomb
start firefox https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository
start firefox https://docs.github.com/en/repositories
start firefox https://en.wikipedia.org/wiki/Run_command
start firefox https://en.wikipedia.org/wiki/Computer
start firefox https://en.wikipedia.org/wiki/Personal_computer
start firefox https://en.wikipedia.org/wiki/1
start firefox https://en.wikipedia.org/wiki/Time
start firefox https://www.merriam-webster.com/dictionary/obvious
start firefox https://www.merriam-webster.com/dictionary/oblivious
start firefox https://www.merriam-webster.com/dictionary/contained
start firefox https://en.wikipedia.org/wiki/Containerization
start firefox https://en.wikipedia.org/wiki/Containerization_\(computing\)
start firefox https://en.wikipedia.org/wiki/OS-level_virtualization
start firefox https://en.wikipedia.org/wiki/Operating_system
start firefox https://en.wikipedia.org/wiki/Kernel_\(operating_system\)
start firefox https://en.wikipedia.org/wiki/Virtualization
start firefox https://en.wikipedia.org/wiki/Virtual_machine
start firefox https://en.wikipedia.org/wiki/Work_of_art
start firefox https://en.wikipedia.org/wiki/Glossary_of_music_terminology#M
start firefox https://www.merriam-webster.com/dictionary/concurrently
start firefox https://www.merriam-webster.com/dictionary/trivially
start firefox https://en.wikipedia.org/wiki/Trivialism
start firefox https://twitter.com/iancoldwater/status/1403019325032779781?lang=en
start firefox https://en.wikipedia.org/wiki/Privilege_escalation
start firefox https://en.wikipedia.org/wiki/Accompaniment
start firefox https://en.wikipedia.org/wiki/Spoiler
start firefox https://en.wikipedia.org/wiki/Experience
start firefox https://www.merriam-webster.com/dictionary/minor
start firefox https://en.wikipedia.org/wiki/Break_in
start firefox https://www.merriam-webster.com/dictionary/say
start firefox https://www.merriam-webster.com/dictionary/out%20loud
start firefox https://www.urbandictionary.com/define.php?term=mind%20bottling
start firefox https://www.merriam-webster.com/dictionary/update
start firefox https://en.wikipedia.org/wiki/Update_\(SQL\)
start firefox https://en.wikipedia.org/wiki/Create,_read,_update_and_delete
start firefox https://en.wikipedia.org/wiki/Desktop_computer
start firefox https://en.wikipedia.org/wiki/Linux
start firefox https://en.wikipedia.org/wiki/Microsoft_Windows
start firefox https://en.wikipedia.org/wiki/Verification_and_validation
start firefox https://en.wikipedia.org/wiki/Copy
start firefox https://en.wikipedia.org/wiki/Xerox
start firefox https://en.wikipedia.org/wiki/Toaster_Strudel
start firefox https://www.merriam-webster.com/dictionary/ready
start firefox https://en.wikipedia.org/wiki/Minced_oath
